apiVersion: apps/v1
kind: Deployment
metadata:
  name: okmi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okmi2
  template:
    metadata:
      labels:
        app: okmi2
    spec:
      containers:
      - image: okteto.dev/okmi2:latest
        name: okmi2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "16cbe554-7498-48be-ad80-a818fc8090b0"
        - name: Vless_Path
          value: "/16cbe554-7498-48be-ad80-a818fc8090b0-vless"
        - name: Vmess_UUID
          value: "16cbe554-7498-48be-ad80-a818fc8090b0"
        - name: Vmess_Path
          value: "/16cbe554-7498-48be-ad80-a818fc8090b0-vmess"
        - name: Trojan_UUID
          value: "16cbe554-7498-48be-ad80-a818fc8090b0"
        - name: Trojan_Path
          value: "/16cbe554-7498-48be-ad80-a818fc8090b0-trojan"
        - name: SS_UUID
          value: "16cbe554-7498-48be-ad80-a818fc8090b0"
        - name: SS_Path
          value: "/16cbe554-7498-48be-ad80-a818fc8090b0-ss"
        - name: Share_Path
          value: "/16cbe554-7498-48be-ad80-a818fc8090b0-share"
